name: Inquira
description: "Swipe Into Knowledge"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  http: ^1.2.0
  flutter_card_swiper: ^6.0.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  xml: ^6.3.0
  another_flushbar: ^1.12.30
  url_launcher: ^6.2.5
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
